remote_theme: pages-themes/midnight@v0.2.0
title: "Название твоего проекта"
description: "Краткое описание того, что делает этот софт или скрипт"
show_downloads: true  # Добавит кнопки скачивания (ZIP/TAR), если это репозиторий с кодом
